# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec8657b5cb45a1b1e6f22cf17cf77fbaa85d8436d4814b27ad506682083391411c2d59a6f9eeccd926bf73a10700b792644223dc25cc0f616735c4c64400114f

test:
  secret_key_base: e059e545ab83dd53a26329526094a418b763090503135684358e06927b158729bc9966409c9e90aa0e77fa9e88331c1f137aeb6efad724a94cd82593f754ede5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
